name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/abutor
      IMAGE_NAME: dauren
      VERSION: 0.1
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Docker image versions
      run: echo "${{ env.VERSION }}.${{ github.run_number }}"

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Api Docker image main
      uses: docker/build-push-action@v3
      with:
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}.${{ github.run_number }}
        build-args: |
          link=https://nuget.pkg.github.com/abutor/index.json
          username=abutor
          password=${{ secrets.GITHUB_TOKEN }}
